# Wrangler configuration for Cloudflare Worker deployment
name = "yly-backend-worker"
main = "src/index.ts"
compatibility_date = "2026-06-11"

env = "production"

[build]
command = "npm install"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "ee2a1d78859245b98546175b2e3d9057"

[vars]
WORKER_ALLOWED_ORIGIN = "https://registrationform.ylyunion.workers.dev/"
